# _______       _   _            _____  _                       _  _____
#|__   __|/\   | \ | |          |  __ \(_)                     | |/ ____|
#   | |  /  \  |  \| |  ______  | |  | |_ ___  ___ ___  _ __ __| | (___  _ ____   __
#   | | / /\ \ | . ` | |______| | |  | | / __|/ __/ _ \| '__/ _` |\___ \| '__\ \ / /
#   | |/ ____ \| |\  |          | |__| | \__ \ (_| (_) | | | (_| |____) | |   \ V /
#    _/_/    \_\_| \_|          |_____/|_|___/\___\___/|_|  \__,_|_____/|_|    \_/
                                                                                    


# Default language :
# Help us translate on https://crowdin.com/project/towns-and-nations-discordsrv ðŸ’–
# Available languages : en,
language: en


## Broadcasting channel
# If the channel does not exist, events will be broadcasted in the default channel
broadcastChannel : "tan"
# Embedded message color
embededColor : "#023E8A"

